### ISSUE TITLE
Problems with Apple Silicon (M1)

### ISSUE THREAD

**Issue by LucaMarconato** [spatial-image/multiscale-spatial-image#77]
I am having some errors related to Apple Silicon and they may originate from some dependencies of `multiscale-spatial-image`. I am using `python3.10` or `python3.11` and installing via `pip` in a fresh conda environment. The installation is successful, but when I import the package I get the following:

```bash
(ome) macbook@MBP-2021 merfish % python -c "import multiscale_spatial_image"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/multiscale_spatial_image/__init__.py", line 15, in <module>
    from .multiscale_spatial_image import MultiscaleSpatialImage
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/multiscale_spatial_image/multiscale_spatial_image.py", line 9, in <module>
    from zarr.storage import BaseStore
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/zarr/__init__.py", line 2, in <module>
    from zarr.codecs import *
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/zarr/codecs.py", line 2, in <module>
    from numcodecs import *
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/numcodecs/__init__.py", line 91, in <module>
    from numcodecs.shuffle import Shuffle
  File "/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/numcodecs/shuffle.py", line 4, in <module>
    from ._shuffle import _doShuffle, _doUnshuffle
ImportError: dlopen(/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/numcodecs/_shuffle.cpython-310-darwin.so, 0x0002): tried: '/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/numcodecs/_shuffle.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/numcodecs/_shuffle.cpython-310-darwin.so' (no such file), '/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/numcodecs/_shuffle.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

Did you encounter this before? Thanks

**Comment by LucaMarconato** [comment]
Fixed with a quick hack:

```
pip uninstall numcodecs
mamba install numcodecs
```

On this topic, it would be useful if `multiscale-spatialo-image` and `spatial-image` were available via conda. Do you have plans to have a conda release?

**Comment by thewtex** [comment]
@LucaMarconato thanks for the report. :+1: for conda packaging, but I do not have the cycles. Help would be welcome.
